Issue/1850
OpenCTI-Platform/opencti pull request #2839
Opened 2023-02-09 12:51 UTC by RomuDeuxfois

### Proposed changes

*
*

### Related issues

*
*

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-02-21 16:31 UTC, richard-julien requested changes

2023-02-21 16:31 UTC, richard-julien commented on opencti-platform/opencti-front/src/private/components/analysis/groupings/GroupingCreation.js
> +  shape = useCustomYup('Grouping', shape, t);
Not a big fan of this notation with a let and a rewrite.
I would prefer a simple
const basicShape = {....}
const shape = useCustomYup('Grouping', basicShape , t);
useCustomYup should also directly generate the shape i think

2023-02-21 16:31 UTC, richard-julien commented on opencti-platform/opencti-front/src/utils/hooks/useEntitySettings.ts
> +export const useCustomYup = <TNextShape extends ObjectShape>(id: string, existingShape: TNextShape, t: (message: string) => string): TNextShape => {
Doest really makes sens to have t in parameter.
Must be removed and use the correct hook directly inside.
const { t } = useFormatter();

2023-02-21 16:31 UTC, richard-julien commented on opencti-platform/opencti-graphql/src/database/middleware-utils.ts
> +import Ajv from 'ajv';
File to rename to schema-validator.ts? to discuss

2023-02-21 16:31 UTC, richard-julien commented on opencti-platform/opencti-graphql/src/database/middleware.js
> +  let metaInputFields;
Use a ternary?

2023-02-21 16:31 UTC, richard-julien commented on opencti-platform/opencti-graphql/src/database/middleware.js
> +    metaInputFields = stixNotCyberObservableFields();
Strange name function stixNotCyberObservableFields

2023-02-21 16:31 UTC, richard-julien commented on opencti-platform/opencti-graphql/src/database/middleware.js
> +    R.omit(schemaRelationsRefDefinition.getName()),
To discuss, not sure to understand how 2 remove can be converted to only one

2023-02-21 16:31 UTC, richard-julien commented on opencti-platform/opencti-graphql/src/database/stix.ts
> -export const CHECK_META_RELATIONSHIP_VALUES: { [k: string]: (fromType: string, toType: string) => boolean } = {
Simple marker to talk about how it works.

2023-02-21 16:31 UTC, richard-julien commented on opencti-platform/opencti-graphql/src/domain/stixDomainObject.js
> +    R.omit(schemaRelationsRefDefinition.getName()),
Same commment about the single omit

2023-02-21 16:31 UTC, richard-julien commented on opencti-platform/opencti-graphql/src/modules/administrativeArea/administrativeArea.ts
> +    xOpenctiStixIds,
Required?  Looks like not defined for other entity

2023-02-21 16:31 UTC, richard-julien commented on opencti-platform/opencti-graphql/src/modules/grouping/grouping.ts
> +    { name: 'context', type: 'string', mandatoryType: 'external', multiple: false, upsert: true },
vocabulary mandatory must be computed from vocabulary-types.ts

2023-02-21 16:31 UTC, richard-julien commented on opencti-platform/opencti-graphql/src/schema/stixCyberObservableRelationship.ts
> +// const xOpenctiLinkedTo: RelationRefDefinition = { // Not in standard
To discuss about relastionships commented in this file

2023-02-21 16:31 UTC, richard-julien commented on opencti-platform/opencti-graphql/src/schema/stixMetaRelationship.ts
> +    mandatoryType: 'no',
Why forcing mandatory to no here?

2023-02-22 11:26 UTC, RomuDeuxfois commented
Bug found : 
- enforce ref enable -> button update but form not valid
- enforce ref enable -> update form and crash
- enforce ref enable > create a new ref and it's direclty add

2023-02-28 01:02 UTC, merged